# Tool for generating possible APA teams.

In [1]:
team = [
    ("victoria", 4, 3),
    ("john",     6, 8),
    ("sam",      4, 3),
    ("josh",     4, 4),
    ("peggy",    2, 2),
    ("richie",   7, 7),
    ("charlie",  4, 4),
    ("jessie",   2, 2),
]

In [2]:
import pandas as pd
from itertools import combinations

def possible_team(team_data, game, min_skill, max_skill):
    """
    Generates a Pandas DataFrame of all possible team lineups based on given criteria.
    
    Args:
    team_data: A list of tuples, each containing (name, 8-ball skill, 9-ball skill).
    game: An integer, 8 for 8-ball, otherwise 9-ball.
    min_skill: The minimum combined skill level for a valid team.
    max_skill: The maximum combined skill level for a valid team.
    
    Returns:
    A Pandas DataFrame containing all possible team lineups.
    """
    
    skill_index = 1 if game == 8 else 2  # Index for relevant skill level
    all_teams = []
    for team in combinations(team_data, 5):
        total_skill = sum([player[skill_index] for player in team])
        if min_skill <= total_skill <= max_skill:
            sorted_team = sorted(team, key=lambda x: (-x[skill_index], x[0])) # Sort by skill descending, then name ascending
            team_row = []
            for player in sorted_team:
                team_row.extend([player[0], player[skill_index]])
            team_row.append(total_skill)  # Add total skill at the end
            all_teams.append(team_row)
    
    columns = [f"Player{(i // 2)+1}" if (i+1) % 2 else f"Skill{i//2 + 1}" for i in range(10)] + ["Team Skill"]
    df = pd.DataFrame(all_teams, columns=columns)
    df = df.sort_values(by=[f"Skill{i}" for i in range(1, 6)], ascending=[False]*5) # Sort by skills
    df = df.reset_index(drop=True)
    return df

In [3]:
possible_team(team, 8, 20, 23)

,Player1,Skill1,Player2,Skill2,Player3,Skill3,Player4,Skill4,Player5,Skill5,Team Skill
0,richie,7,john,6,sam,4,victoria,4,peggy,2,23
1,richie,7,john,6,sam,4,victoria,4,jessie,2,23
2,richie,7,john,6,josh,4,victoria,4,peggy,2,23
3,richie,7,john,6,josh,4,victoria,4,jessie,2,23
4,richie,7,john,6,charlie,4,victoria,4,peggy,2,23
5,richie,7,john,6,charlie,4,victoria,4,jessie,2,23
6,richie,7,john,6,josh,4,sam,4,peggy,2,23
7,richie,7,john,6,josh,4,sam,4,jessie,2,23
8,richie,7,john,6,charlie,4,sam,4,peggy,2,23
9,richie,7,john,6,charlie,4,sam,4,jessie,2,23
10,richie,7,john,6,charlie,4,josh,4,peggy,2,23
11,richie,7,john,6,charlie,4,josh,4,jessie,2,23
12,richie,7,john,6,victoria,4,jessie,2,peggy,2,21
13,richie,7,john,6,sam,4,jessie,2,peggy,2,21
14,richie,7,john,6,josh,4,jessie,2,peggy,2,21
15,richie,7,john,6,charlie,4,jessie,2,peggy,2,21
16,richie,7,charlie,4,josh,4,sam,4,victoria,4,23
17,richie,7,josh,4,sam,4,victoria,4,peggy,2,21
18,richie,7,josh,4,sam,4,victoria,4,jessie,2,21
19,richie,7,charlie,4,sam,4,victoria,4,peggy,2,21
20,richie,7,charlie,4,sam,4,victoria,4,jessie,2,21
21,richie,7,charlie,4,josh,4,victoria,4,peggy,2,21
22,richie,7,charlie,4,josh,4,victoria,4,jessie,2,21
23,richie,7,charlie,4,josh,4,sam,4,peggy,2,21
24,richie,7,charlie,4,josh,4,sam,4,jessie,2,21
25,john,6,charlie,4,josh,4,sam,4,victoria,4,22
26,john,6,josh,4,sam,4,victoria,4,peggy,2,20
27,john,6,josh,4,sam,4,victoria,4,jessie,2,20
28,john,6,charlie,4,sam,4,victoria,4,peggy,2,20
29,john,6,charlie,4,sam,4,victoria,4,jessie,2,20
30,john,6,charlie,4,josh,4,victoria,4,peggy,2,20
31,john,6,charlie,4,josh,4,victoria,4,jessie,2,20
32,john,6,charlie,4,josh,4,sam,4,peggy,2,20
33,john,6,charlie,4,josh,4,sam,4,jessie,2,20

In [4]:
possible_team(team, 9, 20, 23)

,Player1,Skill1,Player2,Skill2,Player3,Skill3,Player4,Skill4,Player5,Skill5,Team Skill
0,john,8,richie,7,josh,4,jessie,2,peggy,2,23
1,john,8,richie,7,charlie,4,jessie,2,peggy,2,23
2,john,8,richie,7,sam,3,victoria,3,peggy,2,23
3,john,8,richie,7,sam,3,victoria,3,jessie,2,23
4,john,8,richie,7,victoria,3,jessie,2,peggy,2,22
5,john,8,richie,7,sam,3,jessie,2,peggy,2,22
6,john,8,charlie,4,josh,4,sam,3,victoria,3,22
7,john,8,charlie,4,josh,4,victoria,3,peggy,2,21
8,john,8,charlie,4,josh,4,victoria,3,jessie,2,21
9,john,8,charlie,4,josh,4,sam,3,peggy,2,21
10,john,8,charlie,4,josh,4,sam,3,jessie,2,21
11,john,8,charlie,4,josh,4,jessie,2,peggy,2,20
12,john,8,josh,4,sam,3,victoria,3,peggy,2,20
13,john,8,josh,4,sam,3,victoria,3,jessie,2,20
14,john,8,charlie,4,sam,3,victoria,3,peggy,2,20
15,john,8,charlie,4,sam,3,victoria,3,jessie,2,20
16,richie,7,charlie,4,josh,4,sam,3,victoria,3,21
17,richie,7,charlie,4,josh,4,victoria,3,peggy,2,20
18,richie,7,charlie,4,josh,4,victoria,3,jessie,2,20
19,richie,7,charlie,4,josh,4,sam,3,peggy,2,20
20,richie,7,charlie,4,josh,4,sam,3,jessie,2,20